[package]
name = "shinichi"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
snafu.workspace = true

[dev-dependencies]
tempfile.workspace = true

[workspace]
resolver = "3"


[workspace.dependencies]
snafu = "0.8"
tempfile = "3.20"
