[package]
name = "shinchi-server"
version = "0.1.0"
edition = "2024"

[dependencies]
shinichi = { path = "../" }
tokio.workspace = true
axum.workspace = true
snafu.workspace = true
parking_lot = "0.12"
